@TM:1383851099
@A:  :"":0:0:0:-1|fpga_mapper output is up to date. No run necessary.
@TM:1383851098
@N:  :"":0:0:0:-1|Running in 64-bit mode
@A:  :"":0:0:0:-1|premap output is up to date. No run necessary.
@TM:1383851048
@W: BN522 :"":0:0:0:-1|Property syn_clock_priority is not supported for this target technology
@TM:1383851051
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@TM:1383851048
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@TM:1383851051
@N: MF667 :"":0:0:0:-1|Clock conversion disabled 
@TM:1383851048
@N: MF667 :"":0:0:0:-1|Clock conversion disabled 
@TM:1383851051
@N: MT320 :"":0:0:0:-1|Timing report estimates place and route data. Please look at the place and route timing report for final timing.
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock.
@TM:1383851098
@N: CG364 :"C:\Microsemi\Libero_v11.0\Synopsys\synplify_G201209MSP1\lib\proasic\smartfusion.v":1141:7:1141:9|Synthesizing module GND
@N: CG364 :"C:\Microsemi\Libero_v11.0\Synopsys\synplify_G201209MSP1\lib\proasic\smartfusion.v":1868:7:1868:9|Synthesizing module VCC
@N: CG364 :"C:\Microsemi\Libero_v11.0\Synopsys\synplify_G201209MSP1\lib\proasic\smartfusion.v":2620:7:2620:11|Synthesizing module RCOSC
@N: CG364 :"N:\373\controller\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":23:7:23:15|Synthesizing module INBUF_MSS
@N: CG364 :"N:\373\controller\component\Actel\SmartFusionMSS\MSS\2.5.106\mss_comps.v":151:7:151:13|Synthesizing module MSS_CCC
@N: CG364 :"N:\373\controller\component\work\controller\controller.v":9:7:9:16|Synthesizing module controller
@N: CG364 :"N:\373\controller\component\work\controller_MSS\controller_MSS.v":9:7:9:20|Synthesizing module controller_MSS
@W: CL159 :"N:\373\controller\component\work\controller_MSS\controller_MSS.v":19:7:19:17|M
@W: CL168 :"N:\373\controller\component\work\controller_MSS\controller_MSS.v":76:0:76:13|M
@TM:1383851051
@N: BN115 :"n:\373\controller\component\work\controller_mss\controller_mss.v":296:37:296:45|M
@TM:1383851098
@W: CL168 :"N:\373\controller\component\work\controller_MSS\controller_MSS.v":334:0:334:22|M
@N: CG364 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":5:7:5:42|Synthesizing module controller_MSS_tmp_MSS_CCC_0_MSS_CCC
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":36:7:36:10|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":37:7:37:14|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":38:7:38:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":39:7:39:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":40:7:40:10|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":41:7:41:14|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":42:7:42:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":43:7:43:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":44:7:44:10|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":45:7:45:14|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":46:7:46:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":47:7:47:15|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":48:7:48:13|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":49:7:49:11|M
@W: CL159 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":50:7:50:13|M
@W: CL157 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":62:7:62:18|M
@TM:1383851051
@W: MO111 :"n:\373\controller\component\work\controller_mss\mss_ccc_0\controller_mss_tmp_mss_ccc_0_mss_ccc.v":62:7:62:18|M
@TM:1383851098
@W: CL157 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":63:7:63:20|M
@TM:1383851051
@W: MO111 :"n:\373\controller\component\work\controller_mss\mss_ccc_0\controller_mss_tmp_mss_ccc_0_mss_ccc.v":63:7:63:20|M
@TM:1383851098
@W: CL157 :"N:\373\controller\component\work\controller_MSS\MSS_CCC_0\controller_MSS_tmp_MSS_CCC_0_MSS_CCC.v":64:7:64:18|M
@TM:1383851051
@W: MO111 :"n:\373\controller\component\work\controller_mss\mss_ccc_0\controller_mss_tmp_mss_ccc_0_mss_ccc.v":64:7:64:18|M
@TM:1383851098
@N: CG364 :"N:\373\controller\component\work\controller_MSS\mss_tshell.v":1:7:1:13|Synthesizing module MSS_APB
@TM:1383851051
@W: MT511 :"n:\373\controller\component\work\controller_mss\mss_tshell_syn.sdc":1:0:1:0|M
@W: MT511 :"n:\373\controller\component\work\controller_mss\mss_tshell_syn.sdc":2:0:2:0|M
@TM:1383851098
@N: CG364 :"N:\373\controller\hdl\controller.v":1:7:1:26|Synthesizing module controller_interface
@W: CL159 :"N:\373\controller\hdl\controller.v":17:12:17:19|M
@N: CG364 :"N:\373\controller\hdl\controller.v":30:7:30:14|Synthesizing module clockDiv
@W: CL159 :"N:\373\controller\hdl\controller.v":30:27:30:30|M
@W: CL169 :"N:\373\controller\hdl\controller.v":34:1:34:6|M
@W: CL189 :"N:\373\controller\hdl\controller.v":34:1:34:6|M
